schema_version = "1.0.0"
id = "greencanvas"
version = "1.0.0"
name = "GreenCanvas"
tagline = "description"
maintainer = "anaritamsmartins"
type = "add-on"
blender_version_min = "3.0.1"
license = [ "SPDX:GPL-3.0-or-later",]
platforms = [ "windows-x64", "macos-x64", "macos-arm64", "linux-x64",]
paths_exclude_pattern = [ "__pycache__/", "/.git/", "/.gitignore/", "/README.md/", "/*.zip", ".mypy_cache/", ".ruff_cache/"]
