schema_version = "1.0.0"
id = "greencanvas"
version = "1.0.0"
name = "GreenCanvas"
tagline = "description"
maintainer = "anaritamsmartins"
type = "add-on"
blender_version_min = "3.0.1"
license = [ "SPDX:GPL-3.0-or-later",]
platforms = [ "windows-x64", "win_amd64", "macos-x64", "macos-arm64", "linux-x64",]
wheels = [ "./wheels/shapely-2.1.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/shapely-2.1.1-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/scipy-1.16.1-cp311-cp311-macosx_12_0_arm64.whl", "./wheels/numpy-2.2.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", "./wheels/numpy-2.3.2-cp311-cp311-win_amd64.whl", "./wheels/scipy-1.16.1-cp311-cp311-manylinux2014_x86_64.manylinux_2_17_x86_64.whl", "./wheels/numpy-2.3.2-cp311-cp311-macosx_11_0_arm64.whl", "./wheels/numpy-2.3.2-cp311-cp311-macosx_10_9_x86_64.whl", "./wheels/shapely-2.1.1-cp311-cp311-macosx_10_9_x86_64.whl", "./wheels/shapely-2.1.1-cp311-cp311-win_amd64.whl", "./wheels/scipy-1.16.1-cp311-cp311-macosx_10_14_x86_64.whl", "./wheels/scipy-1.16.1-cp311-cp311-win_amd64.whl",]
paths_exclude_pattern = [ "__pycache__/", "/.git/", "/.gitignore/", "/README.md/", "/*.zip", ".mypy_cache/", ".ruff_cache/",]
